### ISSUE TITLE
Add ClipPlaneSet method to clip a generic CurveVector

### ISSUE THREAD

**Issue by dassaf4** [iTwin/imodel-native#321]
For imodel02 (connectors).

```[tasklist]
### Tasks
- [x] implement on imodel-native
- [x] port to imodel02
- [x] port to PowerPlatform
- [ ] port to iTwin (if there doesn't already exist a clip method that takes AnyCurve)
```

**Comment by dassaf4** [comment]
Implementation details:
* When CurveVector is open:
  * result can be multiple (disjoint) CurveVectors. What is the preferred return type for this?
  * ignore "invisible" clip planes. There may be two flags on the clipper (or clip plane) that determine this. Look for precedents.
* @EarlinLutz suggests ClipPlanarRegion could be adapted so that when the input is not a region, it just clips the curves.

**Comment by saeeedtorabi** [comment]
More info:
Signature of the new main method: 
`void ClipCurveVector(CurveVectorCR curve, bvector<CurveVectorPtr>& clippedCurves) const`

Signature of the new open-curve method (called by above new method if input is open): 
`bool ClipOpenPath(CurveVectorCR openCurve, bvector<CurveVectorPtr>* pClippedCurves = nullptr, bvector<CurveLocationDetailPair>* pClippedDetails = nullptr) const`

 The method returns false if `openCurve.IsOpenPath` returns false. This allows caller to receive each array only if desired. The most common return value is first in the arglist. Internally, this method can return early (do nothing) if both optional outputs are nullptr; otherwise, it computes the details, and optionally the curves from the details. This way if user doesn't want the clipped curves, the method doesn't waste time computing them, such as it would if `ClipOpenPath` instead returned this array as its return value instead of void. If curve.IsOpenPath, the main method calls this method like so: `this.ClipOpenPath(curve, &clippedCurves)`, passing in the caller's clippedCurves argument; the details aren't needed in this case, so the default nullptr is implied.

**Comment by saeeedtorabi** [comment]
In imodel-native, there's a variant of `CloneBetweenDirectedFractions` which takes curve details. I should add that when I do the port to MS.

**Comment by saeeedtorabi** [comment]
**imodel-native PR**
https://github.com/iTwin/imodel-native/pull/353

**imodel02 PR**
https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/351921

**power-platform PR and PBI**
https://dev.azure.com/bentleycs/PowerPlatform/_workitems/edit/1238279
https://dev.azure.com/bentleycs/PowerPlatform/_git/PPBase/pullrequest/351920
